BEGIN TRANSACTION;
DROP TABLE IF EXISTS "TABLE1";
CREATE TABLE IF NOT EXISTS "TABLE1" (
	"TABLE1PK"	TEXT,
	"FIELD1"	INTEGER,
	"FIELD2"	INTEGER,
	"FIELD3"	INTEGER,
	"FIELD4"	TEXT,
	PRIMARY KEY("TABLE1PK")
);
DROP TABLE IF EXISTS "TABLE2";
CREATE TABLE IF NOT EXISTS "TABLE2" (
	"TABLE2PK"	INTEGER,
	"FIELD2"	TEXT
);
INSERT INTO "TABLE1" VALUES ('1',NULL,NULL,NULL,NULL);
INSERT INTO "TABLE1" VALUES ('2',NULL,NULL,NULL,"WIP");
INSERT INTO "TABLE1" VALUES ('3',1,2,3,"??");
INSERT INTO "TABLE1" VALUES ('4',6,2,3,"??");

COMMIT;
