SELECT ROW_NUMBER() over( order by 1 ) as RowNum
  , 'test#4' AS ID
  , 'E' AS SEVERITY
  , 'TABLE1' AS TABLE_NAME_VALUE
  , 'TABLE1PK' AS TABLE_PK_NAME
  , __LEFT_TABLE.TABLE1PK AS TABLE_PK_VALUE
  , 'FIELD1' AS TABLE_FIELD_NAME
  , __LEFT_TABLE.FIELD1 AS TABLE_FIELD_VALUE
  , null AS FIX
  , 'FIELD1 of TABLE1 is null for key ' || __LEFT_TABLE.TABLE1PK AS MESSAGE
FROM TABLE1 AS __LEFT_TABLE
WHERE ( __LEFT_TABLE.FIELD1 is null )
;
