SELECT ROW_NUMBER() over( order by 1 ) as RowNum
  , 'test#3' AS ID
  , 'E' AS SEVERITY
  , 'TABLE1' AS TABLE_NAME_VALUE
  , null AS TABLE_PK_NAME
  , null AS TABLE_PK_VALUE
  , 'FIELD4' AS TABLE_FIELD_NAME
  , __LEFT_TABLE.FIELD4 AS TABLE_FIELD_VALUE
  , null AS FIX
  , 'FIELD4 is not Open or Close' AS MESSAGE
FROM TABLE1 AS __LEFT_TABLE
WHERE NOT ( ( __LEFT_TABLE.FIELD4 in ("Open","Close") ) )
;
