SELECT ROW_NUMBER() over( order by 1 ) as RowNum
  , 'test#7' AS ID
  , 'E' AS SEVERITY
  , 'TABLE1' AS TABLE_NAME_VALUE
  , 'TABLE1PK' AS TABLE_PK_NAME
  , __LEFT_TABLE.TABLE1PK AS TABLE_PK_VALUE
  , 'FIELD1' AS TABLE_FIELD_NAME
  , __LEFT_TABLE.FIELD1 AS TABLE_FIELD_VALUE
  , null AS FIX
  , 'FIELD1 of TABLE1 is not in table TABLE2 by TABLE2PK' AS MESSAGE
FROM TABLE1 AS __LEFT_TABLE
LEFT JOIN TABLE2 AS __RIGHT_TABLE ON __RIGHT_TABLE.TABLE2PK = __LEFT_TABLE.FIELD1
WHERE ( __RIGHT_TABLE.TABLE2PK is null )
;
