# schema.yaml

setting:
  separator: str(enum('union', ';'), required=True)
  add_row_id: bool(required=True)

validation_rules: list(include('validation_rule'), required=True)

validation_rule:
  id: str(required=False)
  severity: str(enum('I', 'W', 'E'), required=False) # default E present indicates a delete operation
  source: include('table_definition', required=True)
  fk: include('table_definition', required=False)
  where: str(required=False)
  check: include('check_definition', required=False)
  on_success: include('message_definition', required=False)
  on_fail: include('message_definition', required=False)
  fix: include('fix_definition', required=False)

table_definition:
  table: str(required=True)
  pk: str(required=False)
  field: str(required=False)
  joinfield: str(required=False)

check_definition:
  sql: str(required=False)
  value: str(required=False)

message_definition:
  message: str(required=True)

fix_definition:
  update: str(required=False)
  delete: bool(required=False) # True or simplyt present indicates a delete operation
