# .github/workflows/generate_sql.yml
name: Generate SQL from Constraints

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/sample/generic_example.yaml'
      - 'app/constraint-sql-builder.js'
      - '.github/workflows/generate_sql.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/sample/generic_example.yaml'
      - 'app/constraint-sql-builder.js'
      - '.github/workflows/generate_sql.yml'
  workflow_dispatch:
  
permissions:
  contents: write 

jobs:
  generate_sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install js-yaml express js-yaml

      - name: Generate SQL
        id: generate_sql_step
        run: node app/constraint-sql-builder-cli.js app/samples/generic_example.yaml app/output/generic_example.sql
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output SQL to logs \(Optional\)
        run: echo "Generated SQL :\\n${{ steps.generate_sql_step.outputs.sql_output }}"
        
      - name: Commit generated SQL
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Generated SQL"
          file_pattern: generic_example.sql
         
